export const ACTIVITY_LIST_MOBILE_PREVIEW_MAX = 6
export const ACTIVITY_LIST_DESKTOP_PREVIEW_MAX = 8
export const ACTIVITY_LIST_FADE_HEIGHT_PX = 100
export const DASHBOARD_ACTIVITY_BOTTOM_SPACING_PX = 120
